// bit-scope/apps/angular-app/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
	selector: 'app-root',
	templateUrl: './app.component.html',
	styleUrls: ['./app.component.scss']
})
export class AppComponent {
	clicked: boolean = false;

	enableDisable() {
		this.clicked = !this.clicked;
	}
}

<div class='back'>
	<button type='button' (click)='enableDisable()'> Click me! </button>
	<div class='imageDiv'>
		<img src='/assets/images/angular.png' alt='Angular Logo' *ngIf='clicked' />
	</div>
</div>

// bit-scope/apps/react-app/react-app.tsx
import React, {useState} from 'react';
import logoReact from "./assets/react.png";
import "./styles/react-app-style.css";

export default function ReactApp() {
	const [clicked, setClicked] = useState(false);
	const handleClick = () => setClicked(!clicked);

	return (
		<div className='back'>
			<button type='button' onClick={handleClick}> Click me! </button>
			<div className='imageDiv'> {clicked ? <img src={logoReact} alt="React Logo" /> : ""} </div>
		</div>
	);
}
